Myanmar-Data-Tech/MMDT_2025_PY101

nadi-shwe-yee/NadiShweYee_Ex1_Python.ipynb

Completed EX-01 and add reflection.

Project Submission - Ex 01- Nadi Shwe Yee

---

Ex1_Python.ipynb

Clary_Ex01

---

KhineHtetHtetHtun_Ex1_Python.ipynb

Completed Ex01 and added my reflection

Project Submission - Ex01 - Khine Htet Htet Htun

---

Ex1_Python.ipynb

Project Submission - Ex 01-Maymee

---

Pyae Phyoe Maung/pyae_phyoe_maungEx1_Python.ipynb
phyu-phyu-aung/phyuphyuaung_Ex_01.ipynb

လောလောဆယ်တော့ Python ထက် Git hub ကသုံးနေကျမဟုတ်တော့ Exe ထပ်ရတာမှာ အခက်အခဲတွေ ရှိခဲ့ပါတယ်။

Project Submission - Ex01 - Pyae Phyoe Maung

---

nadi-shwe-yee/NadiShweYee_Ex2_datatypes.ipynb
nadi-shwe-yee/NadiShweYee_Ex3_ConditionEx.ipynb

Added Ex2 Datatype notebook and reflection

<Mid-term> Project Submission - Nadi Shwe Yee

---

KhineHtetHtetHtun_Ex2_Python.ipynb

Completed Ex02 and added my reflection

Project Submission - Ex02 - Khine Htet Htet Htun

---

khin-than-htay/Ex2_datatypes_KhinThanHtay.ipynb

In these second and third weeks, I feel like I have learnt a lot about data types exclusively. Teacher gave extensive explanation about data types which I never learnt such as tuple inside tuple and kind of ideas. For me, that is such a new usage of data types. So, I think I can use data type more efficiently in future.
For exercise, I found most of them are manageable and their usage are explained well in teacher's videos. But some are challenging to me such as creating a dictionary table and finding missing number. But after checking teacher's lesson video (1. Dictionary and Set), I understand and am able to generate results. That is end of my reflection. Thank you.

Week 3 assignment submission

---

Ex2_datatypes_winlaiphyu.ipynb
Ex3_ConditionEx_winlaiphyu.ipynb

I didn't well understand for Ex-06 and 08, some point i used AI for reference

Ex2_datatypes_winlaiphyu

---

khin-than-htay/Ex3_ConditionEx_KhinThanHtay.ipynb

In this week, I have to learn about branch (conditional statement). Actually, I have heard of conditional statement like if..elseif...if but I didn't know about the usage branch. So, I have learnt new word about conditional statement and am able to use 1 brand, 2 branches and 3 branches or more.
This week exercises are easy to solve (write a program) for me. 

Ex3_ConditionEx_Submission

---

Copy_of_Ex_2_datatypes.ipynb

Python Exercise 2

---

Ex3_ConditionEx_SharonWai.ipynb

I learned about Conditions and branching (if statements) in this week. I watched Teacher Myo's videos a couple of time and completed the Chapter 4 exercises before the exercise 3. I completed well the exercise 3 questions. I would like to have your feedback on exercise 3 and look forward to more exercises and coding practices in the upcoming weeks. Thank you.

Created using Colab

---

Ex4_Looping.ipynb
mijompar/Ex4_Looping.ipynb

Added solutions for Exercises 1–5 using loops.

Ex4_Looping.ipynb

---

suhtarhlaing/Ex4_Looping_Suhtarhlaing.ipynb
suhtarhlaing/ex3_condition_suhtarhlaing.ipynb

"Completed Ex03 and add reflection1" Done

"Completed Ex03 and add reflection1"

---

phyu-phyu-aung/phyuphyuaung_Ex_04.ipynb

Completed Ex04 and add reflection

Completed Ex04 and add reflection

---

hnincherrywin/hnincherrywin_Ex3_ConditionEx.ipynb

hnincherrywin_Ex3_ConditionEx.ipynb

---

khin-than-htay/Ex4_Looping_KhinThanHtay.ipynb

In this week, I have learnt new function enumerate in "for loop" which is really interesting to me (which can show index and extract single value from a string or list). I am glad that I can learn new things every week. Moreover, I can use nested loops like " if_else" statement inside "while loop" better than before. So, I would like to thank to Teacher Myo for providing such useful lessons and mentor also.
In Ex_01, I found error "string index out of range" while I wrote as teacher's example, so I tried different version which I added both in exercise file. In Ex_04, I used if_else statement as there is no instruction of its usage restriction. Moreover, I referenced while loop explanation (for usage of if_else usage) from book : "A Practical Introduction to Python Programming", by Brian …

Ex_04_Looping

---

wai-mar-lwin/Ex4_Looping_waimarlwin.ipynb
wai-mar-lwin/waimarlwin_Ex_02.ipynb
wai-mar-lwin/waimarwin_Ex_03.ipynb

Completed Ex04 and add reflection

Submission Assignment for Looping Ex4

---

hnincherrywin/hnincherrywin_Ex4_Looping.ipynb

hnincherrywin_Ex4_Looping.ipynb

---

aungyekyaw/Ex0_individual_project_AungYeKyaw.ipynb

Kindly check my code and provide feedback .
Regards,
AYK

adding individual project

---

khin-than-htay/ex0_individual_project_KhinThanHtay.ipynb

Individual project was a bit challenging to me for creating dictionary by using list data in question no.2. But I found some sample codes in supplementary book. In addition to that, for question no.2, I think it is really interesting to write as I can use looping concepts well such as how to break the process if user guesses correct number and how to allow user to play again or not based on their inputs. I faced too many infinite looping in the process but it was fun when the program works properly.

Submission of Individual Project

---

khinehtethtethtun/Khine_Htet_Htet_Htun_Ex0_individual_project.ipynb

IndividualProjectSubmission_Ex0_KhineHtetHtetHtun

---

SharonWai/Ex0_individual_project_SW.ipynb

I completed an individual project for python this week and it is required to use of a Dictionary - compound data type. I watched Tr. Myo's video about compound data type a couple of times, which helped me understand the concept. I understood and answered well the question 1 and 2. For Question 3, I got an assistance from an AI to learn how to create a game. I used "while looping" method to solve the question. I would like to specially thanks to our tutor, Ma Ei Khaing, for her guidance and valuable advice. Her advice is truly helpful for a beginner like me. I would like to appreciate your feedback on my individual project. Thank you.

Sharon wai1

---

suhtarhlaing/Ex0_individual_project_Suhtarhlaing.ipynb

Completed Ex0 individual project and add reflected
Finished individual project. 
I have used AI to understand Question and some of the usage. And Question 3 is very different for me. It is a little hard to understand.

Completed Ex0 individual project and add reflected

---

winlaiphyu/Ex0_indivdiual_project_winlaiphyu.ipynb

I just used AI for Ex-3 cause of i'm not ready to write a complete program and i do revision and learning not only Tr video but also youtube video and other

Completed Ex0 and add reflected

---

NadiShweYee_Ex5_Function.ipynb
NadiShweYee_Ex6-1_Exception1.ipynb
NadiShweYee_Ex6-2_Exception2.ipynb
NadiShweYee_Ex7_Debugging.ipynb

This is my submission for the Ex05 and add reflection.

<Completed Ex5_Function> Project Submission - Nadi Shwe Yee

---

khin-than-htay/Ex5_Function_KhinThanHtay.ipynb

This week is a bit challenging to me. I need to read additional documentation from the suggested book to understand more about user-defined functions and its usage. I am still trying to understand more about debugging as I copied answer for exercise-5 from teacher's file but I tried to keep simple in my answer. And for the number 9, I use ChatGPT about it as I am confused about it. For Sudoku, I understand how to play but I need to get correct and wrong version of Sudoku numbers from ChatGPT. Finally, I need to study additional resources for this week Function topic.

Ex5_Function

---

Clary_Ex5_Function.ipynb
clary/Clary_Ex6_1_Exception1.ipynb
clary/Clary_Ex6_2_Exception2.ipynb
clary/Clary_Ex7_Debugging.ipynb

Submission Ex_5

---

aungyekyaw/AungYeKyaw_Ex5_Function.ipynb

kindly check my code . 
I could not make for the below exercises , I need guide for these.. 
> ex.6, 9 , 10
Thanks and Regards,
Aung Ye Kyaw

adding exercise with reflection

---

nadi-shwe-yee/NadiShweYee_Ex8_Lambda_Ex.ipynb

Completed Ex08 and add reflection

EX8_Lambada Submission - Nadi Shwe Yee
